boot:
- cmd/boot/**/*

tools/cloud:
- cmd/cloud.go
- pkg/ergo/cloud/**/*

tools/code:
- cmd/code.go
- pkg/ergo/codegen/**/*

tools/cvm:
- cmd/cvm.go

tools/debian:
- cmd/debian.go
- pkg/ergo/vm/**/*

tools/debug:
- cmd/debug.go
- pkg/ergo/debug/**/*

tools/exp:
- cmd/exp.go
- pkg/ergo/experimental/**/*

tools/ext:
- cmd/ext.go

tools/k3s:
- cmd/k3s.go
- pkg/ergo/k3s/**/*

tools/ops:
- cmd/ops.go
- pkg/ergo/ops/**/*

tools/plugin:
- cmd/plugin.go
- pkg/ergo/plugin/**/*


tools/repo:
- cmd/repo.go
- pkg/ergo/repo/**/*

tools/service:
- cmd/service.go
- pkg/ergo/service/**/*

common:
  - common/**/*

docs:
  - docs/**/*