run:
  timeout: 10m
  skip-dirs:
    - docs
    - hack
    - internal/pkg/static

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  # default is "colored-line-number"
  format: colored-line-number

linters:
  # TODO: fix errors so that all of the linters below pass.
  # The linters that are commented out, as well as those explicitly disabled,
  # are currently failing.  We should fix those failures or define exclusion
  # rules, and then enable those linters.
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - depguard
    # - deadcode
    # - errcheck
    - exhaustive
    - exportloopref
    - gofmt
    # - gosimple
    - goimports
    - golint
    - govet
    # - gosec
    # - gofumpt
    # - goconst
    # - gocritic
    # - gomnd
    - ineffassign
    - nakedret
    - nolintlint
    - misspell
    # - prealloc
    - predeclared
    - revive
    # - staticcheck
    - stylecheck
    - structcheck
    - thelper
    - tparallel
    - typecheck
    # - unused
    - unconvert
    - unparam
    - varcheck
    - whitespace
    # - wsl

issues:
  exclude-rules:
    - linters:
        - dogsled
      text:  "declaration has 3 blank identifiers"
      path: _test\.go
    - linters:
        - dupl
      path: _test\.go

linters-settings:
  gofmt:
    simplify: true
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 400
  errcheck:
    check-blank: false
  gofumpt:
    extra-rules: false
    lang-version: "1.18"
