run:
  timeout: 10m
  skip-dirs:
    - docs
    - hack

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  # default is "colored-line-number"
  format: colored-line-number

linters:
  # TODO: fix errors so that all of the linters below pass.
  # The linters that are commented out, as well as those explicitly disabled,
  # are currently failing.  We should fix those failures or define exclusion
  # rules, and then enable those linters.
  disable-all: true
  enable:
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - unused
    - varcheck
    - staticcheck
    - dogsled
    - gofmt
    - goimports
    # - gosec
    - misspell
    - nakedret
    - stylecheck
    - structcheck
    - golint
    - unconvert
    - unparam
    - whitespace
#  disable:
#    - errcheck
issues:
  exclude-rules:
    - linters:
        - dogsled
      text:  "declaration has 3 blank identifiers"
      path: _test\.go
    - linters:
        - dupl
      path: _test\.go

linters-settings:
  gofmt:
    simplify: true
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 400
  errcheck:
    check-blank: false
