name: Changelog

on:
  push:
    tags:
      - "*"

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - run: git fetch --prune --prune-tags
      - run: git tag -l 'v*'
      - run: ./hack/build/changelog.sh > CHANGELOG.md
      - uses: peter-evans/create-pull-request@v5
        with:
          title: 'docs: updated CHANGELOG.md'
          commit-message: 'docs: updated CHANGELOG.md'
          branch: create-pull-request/changelog
          signoff: true
