name: ci
on:
  push:
    branches:
    - develop
    - feat*
jobs:
  build:
    name: build ergo tools
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.17.x
    - name: install gox
      run: |
          echo "install gox"
          go get -u github.com/mitchellh/gox
    - name: install ghr
      run: |
          echo "install ghr"
          go get -u github.com/tcnksm/ghr
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: build ergo
      run: |
          export TZ='Asia/Shanghai'
          export PATH=$PATH:$(go env GOPATH)/bin
          make docker
          ./dist/ergo_linux_amd64 version
          make doc
    - name: docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs