name: Release

env:
  TZ: Asia/Shanghai
  GO_VERSION: '1.20'

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Release ergo tools
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install upx
        run: |
          echo "install upx"
          sudo apt-get update -qq
          sudo apt-get install -y upx
      - uses: actions/checkout@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Publish .deb & .rpm to Gemfury
        env:
          FURY_TOKEN: ${{ secrets.APT }}
        run: |
          for filename in dist/*.deb; do
            echo "Pushing $filename to apt repository"
            curl -F package=@$filename https://${FURY_TOKEN}@push.fury.io/ysicing/
          done
          for filename in dist/*.rpm; do
            echo "Pushing $filename to rpm repository"
            curl -F package=@$filename https://${FURY_TOKEN}@push.fury.io/ysicing/
          done
      - name: Publish Tap
        run: |
          ./gen.sh
