name: tag
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: build ergo tools
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: install gox
        run: |
          echo "install gox"
          go install github.com/mitchellh/gox@latest

      - name: install ghr
        run: |
          echo "install ghr"
          go install github.com/tcnksm/ghr@latest
      - name: install upx
        run: |
          echo "install upx"
          sudo apt-get update -qq
          sudo apt-get install -y upx
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: build ergo
        run: |
          export TZ='Asia/Shanghai'
          export PATH=$PATH:$(go env GOPATH)/bin
          make getbin
          make build
          make upx
          make dpush

          pushd dist
          sha256sum ergo_darwin_amd64 > ergo_darwin_amd64.sha256sum
          sha256sum ergo_linux_amd64 > ergo_linux_amd64.sha256sum
          sha256sum ergo_windows_amd64.exe > ergo_windows_amd64.sha256sum
          sha256sum ergo_darwin_arm64 > ergo_darwin_arm64.sha256sum
          sha256sum ergo_linux_arm64 > ergo_linux_arm64.sha256sum
          popd
          ./gen.sh
          cat version.txt | grep -E '(beta|rc)' && (pre-release) || (make release)
          make deb
        env:
          GITHUB_RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          DEBTOKEN: ${{ secrets.APT }}
