name: tests
on:
  push:
jobs:
  build:
    name: build ergo tools
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x
      - name: install gox
        run: |
          echo "install gox"
          go get -u github.com/mitchellh/gox
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build ergo
        run: |
          export TZ='Asia/Shanghai'
          export PATH=$PATH:$(go env GOPATH)/bin
          make build
          ./dist/ergo_linux_amd64 version
